export enum PASSWORDS {
  TOO_WEAK,
  WEAK,
  MEDIUM,
  STRONG,
  VERY_STRONG
}

export const PASSWORD_SCORE = {
  [PASSWORDS.TOO_WEAK]: 15,
  [PASSWORDS.WEAK]: 30,
  [PASSWORDS.MEDIUM]: 55,
  [PASSWORDS.STRONG]: 70,
  [PASSWORDS.VERY_STRONG]: 85
}
