export enum PASSWORDS {
  TOO_WEAK,
  WEAK,
  MEDIUM,
  STRONG,
  VERY_STRONG
}

export const PASSWORD_SCORE = {
  [PASSWORDS.TOO_WEAK]: 15,
  [PASSWORDS.WEAK]: 35,
  [PASSWORDS.MEDIUM]: 60,
  [PASSWORDS.STRONG]: 80,
  [PASSWORDS.VERY_STRONG]: 100
}
