export { isEmail } from './lib/isEmail'
export { isString } from './lib/isString'
export { isURL } from './lib/isUrl'
export { isTel } from './lib/isTel'
export { isInteger } from './lib/isInteger'
export { isPassword } from './lib/isPassword'
