export { isEmail } from './isEmail'
export { isString } from './isString'
export { isURL } from './isUrl'
export { isTel } from './isTel'
export { isInteger } from './isInteger'
export { isAccepted } from './isAccepted'
